# Generated by Django 2.2.7 on 2019-12-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
